/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Pixel_Monster (https://sketchfab.com/ar.jethin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/indian-man-in-kurta-a7fcb7ce36984b1b860ac7e476033bb1
Title: Indian Man In Kurta 1.845
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 3, 0, 0]} scale={1.600}>
          <group name="5b813d0c081e45bb9deed993557b1144fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="AvatarRoot">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="AvatarBody" />
                    <group name="AvatarEyelashes" />
                    <group name="AvatarHead" />
                    <group name="AvatarLeftCornea" />
                    <group name="AvatarLeftEyeball" />
                    <group name="AvatarRightCornea" />
                    <group name="AvatarRightEyeball" />
                    <group name="AvatarTeethLower" />
                    <group name="AvatarTeethUpper" />
                    <group name="haircut" />
                    <group name="outfit" />
                    <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.AvatarBody} skeleton={nodes.Object_7.skeleton} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.AvatarEyelashes} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.AvatarHead} skeleton={nodes.Object_9.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.AvatarLeftCornea} skeleton={nodes.Object_10.skeleton} />
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.AvatarLeftEyeball} skeleton={nodes.Object_11.skeleton} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.AvatarRightCornea} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.AvatarRightEyeball} skeleton={nodes.Object_13.skeleton} />
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.AvatarTeethLower} skeleton={nodes.Object_14.skeleton} />
                    <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.AvatarTeethUpper} skeleton={nodes.Object_15.skeleton} />
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.haircut} skeleton={nodes.Object_16.skeleton} />
                    <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.outfit} skeleton={nodes.Object_17.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')



